#!/bin/sh

# build libcallback.so
cd /src/libcallback
PATH=$PATH:/src/libcallback/mips-gcc472-glibc216-64bit/bin
mips-linux-uclibc-gnu-gcc -fPIC -shared -o libcallback.so filesnooper.c -ldl
mkdir -p /src/atomcam_configs/overlay_rootfs/lib/modules/
cp libcallback.so /src/atomcam_configs/overlay_rootfs/lib/modules/

# build kernel and rootfs
cd /openmiko/build/buildroot-2016.02
cp /src/atomcam_configs/openmiko.config .config
make oldconfig
make clean
make

# sdcard image
cp output/images/uImage.lzma /src
cp output/images/rootfs.ext2 /src
