#!/bin/sh

# mipsel-gcc for uLibc
cd /openmiko/build
git clone https://github.com/Dafang-Hacks/mips-gcc472-glibc216-64bit.git
PATH=$PATH:/openmiko/build/mips-gcc472-glibc216-64bit/bin

# build libcallback.so
cd /src/atomcam_configs/libcallback
mips-linux-uclibc-gnu-gcc -fPIC -shared -o libcallback.so filesnooper.c setlinebuf.c mmc_format.c -ldl
mkdir -p /src/atomcam_configs/overlay_rootfs/lib/modules/
cp libcallback.so /src/atomcam_configs/overlay_rootfs/lib/modules/

# build webpage
PATH=$PATH:/root/.nvm/versions/node/v16.11.1/bin
cd /src/atomcam_configs/web
npm install -g npm
npm install
./node_modules/.bin/webpack --mode production --progress
cp -pr frontend/* /src/atomcam_configs/overlay_rootfs/var/www

# set version
cp /src/atomcam_configs/atomhack.ver /src/atomcam_configs/overlay_rootfs/etc

# build kernel and rootfs
cd /openmiko/build/buildroot-2016.02
cp /src/atomcam_configs/openmiko.config .config
make oldconfig
make clean
make

# sdcard image
cp output/images/uImage.lzma /src
cp output/images/rootfs.ext2 /src
