#!/bin/sh
# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
sleep 1

mkdir -p /sdcard
mount -t vfat /dev/mmcblk0p1 /sdcard -o rw,umask=0000,dmask=0000
mkdir -p /newroot
mount -t ext2 -o loop /sdcard/rootfs_hack.ext2 /newroot
mkdir -p /newroot/dev
mkdir -p /newroot/sys

mount --move /dev /newroot/dev
mount --move /sys /newroot/sys
mount --move /proc /newroot/proc
mkdir -p /newroot/media/mmc
mount --move /sdcard /newroot/media/mmc

exec busybox switch_root /newroot /sbin/init
