#!/bin/sh

HACK_INI=/media/mmc/hack.ini

STORAGE_SDCARD_PATH=$(awk -F "=" '/STORAGE_SDCARD_PATH *=/ {print $2}' $HACK_INI)
STORAGE_CIFS_PATH=$(awk -F "=" '/STORAGE_CIFS_PATH *=/ {print $2}' $HACK_INI)
STORAGE_SDCARD_REMOVE=$(awk -F "=" '/STORAGE_SDCARD_REMOVE *=/ {print $2}' $HACK_INI)
STORAGE_SDCARD_REMOVE_DAYS=$(awk -F "=" '/STORAGE_SDCARD_REMOVE_DAYS *=/ {print $2}' $HACK_INI)
if [ "$STORAGE_SDCARD_PATH" = "" ] && [ "$STORAGE_CIFS_PATH" = "" ] && [ "$STORAGE_SDCARD_REMOVE" = "" ] && [ "$STORAGE_SDCARD_REMOVE_DAYS" != "" ] ; then
  RECORDING_PATH=$(awk -F "=" '/RECORDING_PATH *=/ {gsub(/\\/, "/");print $2}' $HACK_INI)
  STORAGE_REMOVE=$(awk -F "=" '/STORAGE_REMOVE *=/ {print $2}' $HACK_INI)
  STORAGE_REMOVE_DAYS=$(awk -F "=" '/STORAGE_REMOVE_DAYS *=/ {print $2}' $HACK_INI)
  STORAGE_CIFSSERVER=$(awk -F "=" '/STORAGE_CIFSSERVER *=/ {gsub(/\\/, "/");print $2}' $HACK_INI)
  grep -v '^RECORDING_PATH *=' $HACK_INI | grep -v '^STORAGE_REMOVE *=' | grep -v '^STORAGE_REMOVE_DAYS *=' | grep -v 'STORAGE_CIFSSERVER *=' > ${HACK_INI}_new
  echo "STORAGE_SDCARD_PATH=${RECORDING_PATH}" >> ${HACK_INI}_new
  echo "STORAGE_SDCARD_REMOVE=${STORAGE_REMOVE}" >> ${HACK_INI}_new
  echo "STORAGE_SDCARD_REMOVE_DAYS=${STORAGE_REMOVE_DAYS}" >> ${HACK_INI}_new
  echo "STORAGE_CIFSSERVER=${STORAGE_CIFSSERVER}" >> ${HACK_INI}_new
  echo "STORAGE_CIFS_PATH=${RECORDING_PATH}" >> ${HACK_INI}_new
  mv -f ${HACK_INI}_new ${HACK_INI}
  cp ${HACK_INI} /tmp/hack.ini
  chmod 666 /tmp/hack.ini
fi

RTSP_VIDEO0=$(awk -F "=" '/RTSP_VIDEO0 *=/ {print $2}' $HACK_INI)
RTSP_AUDIO0=$(awk -F "=" '/RTSP_AUDIO0 *=/ {print $2}' $HACK_INI)
if [ "$RTSP_VIDEO0" = "" ] && [ "$RTSP_AUDIO0" = "" ] ; then
  RTSPSERVER=$(awk -F "=" '/RTSPSERVER *=/ {print $2}' $HACK_INI)
  RTS_AUDIO=$(awk -F "=" '/RTS_AUDIO *=/ {print $2}' $HACK_INI)
  grep -v '^RTSPSERVER *=' $HACK_INI | grep -v '^RTS_AUDIO *=' > ${HACK_INI}_new
  echo "RTSP_VIDEO0=${RTSPSERVER}" >> ${HACK_INI}_new
  echo "RTSP_AUDIO0=${RTS_AUDIO}" >> ${HACK_INI}_new
  mv -f ${HACK_INI}_new ${HACK_INI}
  cp ${HACK_INI} /tmp/hack.ini
  chmod 666 /tmp/hack.ini
fi

for i in `ls /media/mmc/atomhack.log.? /media/mmc/healthcheck.log.? 2> /dev/null`
do
  gzip $i
done
