#!/bin/sh
#
# Start webhook for atomcam
#

case "$1" in
  start)
    /scripts/hack_ini_reconfig
    rm -f /etc/init.d/S32reconfig
  ;;
  stop)
  ;;
  restart|reload)
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
