#!/bin/sh
#
# Start webhook for atomcam
#

case "$1" in
  start)
    [ -f /media/mmc/hack.ini ] || touch /media/mmc/hack.ini
    cp /media/mmc/hack.ini /tmp/hack.ini
    chmod 666 /tmp/hack.ini
    mkdir -p /tmp/log
  ;;
  stop)
  ;;
  restart|reload)
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
