#!/bin/sh
#
# Start webhook for atomcam
#
#
# /atom          : squashfs  /var/atom_root.squashfs (copy from /dev/mtdblock2 : SPI Flash)
# /atom/system   : squashfs  /dev/mtdblock3  (SPI Flash)
# /atom/configs  : ext2      /media/mmc/configs copy from /dev/mtdblock6(jffs2)
# /configs       : ext2      /media/mmc/tools_configs
# ---- The following are bind mounts ----
# /atom/run -> /run
# /atom/tmp -> /tmp
# /atom/media -> /media
# /atom/tmp/system/lib -> /lib
# /atom/usr -> /tmp/system/usr
# /atom/usr/lib -> /usr/lib
# /atom/etc -> /tmp/system/etc
# /atom/sbin -> /tmp/system/sbin
# /configs/etc/ssh -> /etc/ssh
# /configs/etc/lighttpd -> /etc/lighttpd
# /configs/etc/wpa_supplicant.conf -> /etc/wpa_supplicant.conf
# /configs/root -> /root
# /configs/crontabs -> /var/spool/cron/crontabs

case "$1" in
  start)
    ss=`ls -l /media/mmc/atom_root.squashfs | awk '{print $5}'`
    [ "$ss" = "3997696" ] || dd if=/dev/mtdblock2 of=/media/mmc/atom_root.squashfs bs=16k count=244
    mount -t squashfs /media/mmc/atom_root.squashfs /atom
    mount -t squashfs /dev/mtdblock3 /atom/system
    [ -f /media/mmc/configs ] || ( dd if=/dev/zero of=/media/mmc/configs bs=1M count=1 && mkfs.ext2 -F /media/mmc/configs )
    mount -t ext2 -o loop /media/mmc/configs /atom/configs
    if [ ! -f /atom/configs/.product_config -o ! -f /atom/configs/.user_config ] ; then
      echo "rebuild configs" >> /media/mmc/atomhack.log
      mount -t jffs2 /dev/mtdblock6 /mnt
      cp -p /mnt/.* /mnt/* /atom/configs 2> /dev/null
      umount /mnt
    fi
    [ -f /media/mmc/tools_configs ] || ( dd if=/dev/zero of=/media/mmc/tools_configs bs=1M count=1 && mkfs.ext2 -F /media/mmc/tools_configs )
    mount -t ext2 -o loop /media/mmc/tools_configs /configs
    if [ ! -d /configs/etc/ssh ] ; then
      mkdir -p /configs/etc/ssh
      cp -pr /etc/ssh/* /configs/etc/ssh
    fi
    if [ ! -f /configs/etc/wpa_supplicant.conf ] ; then
      cp -pr /etc/wpa_supplicant.conf /configs/etc
    fi
    if [ ! -d /configs/etc/lighttpd ] ; then
      mkdir -p /configs/etc/lighttpd
      cp -pr /etc/lighttpd/* /configs/etc/lighttpd
    fi
    if [ ! -d /configs/root ] ; then
      mkdir -p /configs/root
      cp -pr /root/.profile /configs/root
    fi
    if [ ! -d /configs/crontabs ] ; then
      mkdir -p /configs/crontabs
      cp -pr /var/spool/cron/crontabs/root /configs/crontabs
    fi
    echo 3 > /proc/sys/vm/drop_caches
    sync

    mount -t proc proc /atom/proc
    mount -o rbind /dev /atom/dev
    mount -t sysfs sysfs /atom/sys
    mount -o bind /run /atom/run
    mount -o bind /tmp /atom/tmp
    mount -o rbind /media /atom/media
    mkdir -p /tmp/system/lib
    mount -o bind /lib /atom/tmp/system/lib
    cp -pr /atom/usr /tmp/system
    mkdir -p /tmp/system/usr/lib
    mount -o bind /tmp/system/usr /atom/usr
    mount -o bind /usr/lib /atom/usr/lib
    cp -pr /atom/etc /tmp/system
    mount -o bind /tmp/system/etc /atom/etc
    cp -pr /atom/sbin /tmp/system
    mount -o bind /tmp/system/sbin /atom/sbin
    mount -o rbind /configs/etc/ssh /etc/ssh
    mount -o rbind /configs/etc/lighttpd /etc/lighttpd
    mount -o rbind /configs/etc/wpa_supplicant.conf /etc/wpa_supplicant.conf
    mount -o rbind /configs/root /root
    mount -o rbind /configs/crontabs /var/spool/cron/crontabs
    mkdir -p /media/mmc/update
    mkdir -p /media/mmc/tmp
    rm -f /media/mmc/tmp/*
    rm -f /media/mmc/timelapse.info
  ;;
  stop)
  ;;
  restart|reload)
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
