#!/bin/sh
#
# Start crond
#

start() {
	printf "Starting crond: "
	/usr/sbin/crond -l 8
	echo "OK"
}

stop() {
	printf "Stopping crond: "
	killall crond
	echo "OK"
}

case "$1" in
  start)
    start
	;;
  stop)
    stop
	;;
  restart|reload)
    stop
    start
	;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
