#!/bin/sh
#
# set hostname
#


case "$1" in
  start)
	  [ ! -f /media/mmc/hostname ] && echo "atomcam" > /media/mmc/hostname
    mount -o bind /media/mmc/hostname /etc/hostname
	  hostname -F /media/mmc/hostname
	;;
  stop)
    umount /etc/hostname
	;;
  restart|reload)
	  "$0" stop
	  "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

