#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
    /scripts/network_init.sh start
	;;
  stop)
    /scripts/network_init.sh stop
	;;
  restart|reload)
    /scripts/network_init.sh restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

