#!/bin/sh
#
# Start network time daemon
#

case "$1" in
  start)
    while ! ping -c 1 ntp.nict.jp > /dev/null 2>&1
    do
      sleep 0.5
    done
    logger -s "Starting ntpd: "
    /usr/sbin/ntpd -p ntp.nict.jp
    [ $? == 0 ] && logger -s "OK" || logger -s "FAIL"
  ;;
  stop)
    logger -s "Stopping ntpd: "
    killall ntpd
    [ $? == 0 ] && logger -s "OK" || logger -s "FAIL"
  ;;
  restart|reload)
    "$0" stop
    "$0" start
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
