#!/bin/sh
#
# Start webhook for atomcam
#

case "$1" in
  start)
    mkfifo /var/run/atomapp
    /scripts/webhook.sh &
  ;;
  stop)
    killall webhook.sh > /dev/null 2>&1
  ;;
  restart|reload)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
