#!/bin/sh
#
# build atomcam environment
#
#
# ---- The following are bind mounts ----
# /atom/tmp/system/bin -> /atom_patch/system_bin
# /atom/tmp/system/lib -> /lib
# /atom/tmp/system/usr/lib -> /usr/lib
# /atom/bin -> /atom_patch/bin
# /atom/sbin -> /atom_patch/sbin
# /atom/etc -> /atom_patch/etc

case "$1" in
  start)
    echo "setup atomcam environment"

    mkdir -p /tmp/system/bin
    mount -o bind /atom_patch/system_bin /atom/tmp/system/bin
    mount -o bind /usr/bin/curl /atom/tmp/system/bin/curl
    mount -o bind /usr/bin/find /atom/tmp/system/bin/find
    mount -o bind /bin/busybox /atom/tmp/system/bin/busybox
    mkdir -p /tmp/system/lib
    mount -o bind /lib /atom/tmp/system/lib
    mkdir -p /tmp/system/usr/lib
    mount -o bind /usr/lib /atom/tmp/system/usr/lib

    mount -o bind /atom/bin/busybox /atom_patch/bin/busybox
    mount -o bind /atom/bin/hostapd /atom_patch/bin/hostapd
    mount -o rbind /atom_patch/bin /atom/bin

    mount -o bind /atom/sbin/flash_erase /atom_patch/sbin/flash_erase
    mount -o rbind /atom_patch/sbin /atom/sbin

    mount -o bind /atom_patch/etc /atom/etc

    mount -o bind /atom_patch/bin/null.sh /atom/usr/boa/boa
    mount -o bind /atom_patch/bin/null.sh /atom/system/bin/restart_wlan0.sh

    /scripts/set_crontab.sh
    touch /tmp/resolv.conf

    insmod /lib/modules/3.10.14__isvp_swan_1.0__/extra/v4l2loopback.ko video_nr=0,1,2
    chroot /atom /tmp/system/bin/atom_init.sh
    [ -f /media/mmc/atom-debug ] && exit 0
    
    count=0
    while :
    do
      res=`/scripts/cmd audio` 2> /dev/null
      [ "$res" = "on" -o "$res" = "off" ] && echo "=== iCamera_app callback OK ====" && break;
      sleep 0.5
      let count++
      if [ 20 -le $count ] ; then
        echo "=== iCamera_app callback error ==="
        sync
        sync
        sync
        reboot
        break
      fi
    done
    /scripts/cmd timelapse restart
    [ -x /media/mmc/post_icamera.sh ] && /media/mmc/post_icamera.sh start
  ;;
  stop)
    [ -x /media/mmc/post_icamera.sh ] && /media/mmc/post_icamera.sh stop
    killall -SIGUSR2 iCamera_app
    umount /atom/system/bin/restart_wlan0.sh
    umount /atom/usr/boa/boa
    umount /atom_patch/sbin/flash_erase
    umount /atom_patch/bin/hostapd
    umount /atom_patch/bin/busybox
    umount /atom/tmp/system/usr/lib
    umount /atom/tmp/system/lib
    umount /atom/tmp/system/bin/busybox
    umount /atom/tmp/system/bin/find
    umount /atom/tmp/system/bin/curl
    umount /atom/tmp/system/bin
    umount /atom/etc
    umount /atom/sbin
    umount /atom/bin
  ;;
  restart|reload)
    "$0" stop
    "$0" start
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
