#!/bin/sh
#
# build atomcam environment
#

case "$1" in
  start)
    echo "setup atomcam environment"
    mkdir -p /tmp/system/bin
    cp /scripts/atom_init.sh /tmp/system/bin
    cp /scripts/mount_cifs.sh /tmp/system/bin/mount_cifs
    cp /scripts/rm.sh /tmp/system/bin/rm
    cp /scripts/mv.sh /tmp/system/bin/mv
    cp /scripts/killall.sh /tmp/system/bin/killall
    cp /scripts/null.sh /tmp/system/bin/wpa_supplicant
    cp /scripts/wpa_cli.sh /tmp/system/bin/wpa_cli
    cp /scripts/null.sh /tmp/system/bin/udhcpc
    cp /scripts/null.sh /tmp/system/sbin/ifconfig
    cp /usr/bin/curl /tmp/system/bin
    cp /usr/bin/find /tmp/system/bin/find_libc
    cp /scripts/null.sh /tmp/system/usr/boa/boa
    cp /etc/nsswitch.conf /tmp/system/etc
    cp /bin/busybox /tmp/system/bin
    mount -o bind /scripts/null.sh /atom/system/bin/restart_wlan0.sh
    /scripts/set_crontab.sh
    touch /tmp/resolv.conf

    insmod /lib/modules/3.10.14__isvp_swan_1.0__/extra/v4l2loopback.ko video_nr=0,1
    chroot /atom /tmp/system/bin/atom_init.sh
    renice -10 `pidof iCamera_app`
    count=0
    while :
    do
      res=`/scripts/cmd audio` 2> /dev/null
      [ "$res" = "on" -o "$res" = "off" ] && echo "=== iCamera_app callback OK ====" && break;
      sleep 0.5
      let count++
      if [ 20 -le $count ] ; then
        echo "=== iCamera_app callback error ==="
        sync
        sync
        sync
        reboot
        break
      fi
    done
    /scripts/cmd timelapse restart
  ;;
  stop)
    killall -SIGUSR2 iCamera_app
  ;;
  restart|reload)
    "$0" stop
    "$0" start
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
