#!/bin/sh
#
# Start webcmd for atomcam
#

case "$1" in
  start)
    /scripts/webcmd.sh &
    /scripts/cruise.sh &
  ;;
  stop)
    killall webcmd.sh
    killall tail
    killall cruise.sh > /dev/null 2>&1
  ;;
  restart|reload)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
