#!/bin/sh
#
# Start webcmd for atomcam
#

case "$1" in
  start)
    /scripts/webcmd.sh &
    /scripts/cruise.sh &
  ;;
  stop)
    kill `pidof webcmd.sh`
    kill `pidof cruise.sh`
  ;;
  restart|reload)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
