#!/bin/sh
#
# rtspserver
#

case "$1" in
  start)
    /scripts/rtspserver.sh &
    ;;
  stop)
    /scripts/rtspserver.sh off
	  ;;
  restart|reload)
      /scripts/rtspserver.sh off
      /scripts/rtspserver.sh
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

