#!/bin/sh

[ -f /etc/samba/smb.conf ] || exit 0

case "$1" in
  start)
    mkdir -p /var/log/samba
    mkdir -p /tmp/samba/lib/private
    mount -o bind /tmp/samba/lib /var/lib/samba
  	/scripts/samba.sh on &
  ;;
  stop)
  	/scripts/samba.sh off
    umount /var/lib/samba
	;;
  restart)
  	/scripts/samba.sh off
  	/scripts/samba.sh on &
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

