#!/bin/sh
#
# Start ftp client and scheduler
#

case "$1" in
    start)
	/scripts/honeylab.sh &
	;;
    stop)
	;;
    restart|reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
