#!/bin/sh

[ -f /etc/samba/smb.conf ] || exit 0
mkdir -p /var/log/samba
mkdir -p /tmp/sdcard
ln -s /media/mmc/record /tmp/sdcard
ln -s /media/mmc/alarm_record /tmp/sdcard
ln -s /media/mmc/time_lapse /tmp/sdcard

HACK_INI=/media/mmc/hack.ini
touch $HACK_INI
STORAGE_SDCARD_PUBLISH=$(awk -F "=" '/STORAGE_SDCARD_PUBLISH *=/ {print $2}' $HACK_INI)

start() {
  if [ "$STORAGE_SDCARD_PUBLISH" = "on" ]; then
    (
    printf "Starting SMB services: "
    smbd -D
    [ $? = 0 ] && echo "OK" || echo "FAIL"

    printf "Starting NMB services: "
    nmbd -D
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ) &
  fi
}

stop() {
  printf "Shutting down SMB services: "
  pidof smbd > /dev/null && kill -9 `pidof smbd`
  [ $? = 0 ] && echo "OK" || echo "FAIL"

  printf "Shutting down NMB services: "
  pidof nmbd > /dev/null && kill -9 `pidof nmbd`
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	start
}

reload() {
  printf "Reloading smb.conf file: "
  kill -HUP `pidof smbd`
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	reload
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?

