#!/bin/sh
#
# build atomcam environment
#

case "$1" in
  start)
  echo "setup atomcam environment"
  mkdir -p /atom
  mount -t squashfs /dev/mtdblock2 /atom
  mount -t squashfs /dev/mtdblock3 /atom/system
  mount -t jffs2 /dev/mtdblock6 /atom/configs
  mount -t proc proc /atom/proc
  mount -o rbind /dev /atom/dev
  mount -t sysfs sysfs /atom/sys
  mount -o bind /run /atom/run
  mount -o bind /tmp /atom/tmp
  mount -o rbind /media /atom/media
  mkdir -p /tmp/system/bin
  cp /scripts/atom_init.sh /tmp/system/bin
  cp /scripts/mount_cifs.sh /tmp/system/bin/mount_cifs
  cp /scripts/rm.sh /tmp/system/bin/rm
  cp /scripts/mv.sh /tmp/system/bin/mv
  cp /usr/bin/curl /tmp/system/bin
  cp /usr/bin/find /tmp/system/bin/find_libc
  mkdir -p /tmp/system/modules
  mkdir -p /tmp/system/lib
  mount -o bind /lib /atom/tmp/system/lib
  cp -pr /atom/usr /tmp/system
  mkdir -p /tmp/system/usr/lib
  mount -o bind /tmp/system/usr /atom/usr
  cp /scripts/boa.sh /tmp/system/usr/boa/boa
  mount -o bind /usr/lib /atom/usr/lib
  cp -pr /atom/etc /tmp/system
  cp /etc/nsswitch.conf /tmp/system/etc
  mount -o bind /tmp/system/etc /atom/etc
  cp /bin/busybox /tmp/system/bin
  [ -f /media/mmc/hack.ini ] || touch /media/mmc/hack.ini
  cp /media/mmc/hack.ini /tmp/hack.ini
  chmod 666 /tmp/hack.ini
  /scripts/set_crontab.sh
  mkdir -p /media/mmc/update

  insmod /lib/modules/3.10.14__isvp_swan_1.0__/extra/v4l2loopback.ko video_nr=1
  chroot /atom /tmp/system/bin/atom_init.sh
  count=0
  while ! ifconfig wlan0 | grep 'inet addr'
  do
    sleep 1
    let count++
    [ 30 -le $count ] && break
  done
  renice -10 `pidof iCamera_app`
  ;;
  stop)
  killall -SIGUSR2 iCamera_app
  ;;
  restart|reload)
  "$0" stop
  "$0" start
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
