#!/bin/sh
#
# rtspserver
#

case "$1" in
  start)
    echo "rtspserver start"
    (
      while ! ifconfig wlan0 | grep 'inet addr' > /dev/null
      do
        sleep 1
      done
      /scripts/rtspserver.sh
    ) &
    ;;
  stop)
    echo "rtspserver stop"
    /scripts/rtspserver.sh off
	  ;;
  restart|reload)
      /scripts/rtspserver.sh off
      /scripts/rtspserver.sh
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

