#!/bin/sh

[ -f /etc/samba/smb.conf ] || exit 0
mkdir -p /var/log/samba

case "$1" in
  start)
  	/scripts/samba.sh on &
  ;;
  stop)
  	/scripts/samba.sh off
	;;
  restart)
  	/scripts/samba.sh off
  	/scripts/samba.sh on &
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

